json.cash_balance user["cash_balance"]
json.email_address user["email_address"]
json.expiry_date user["expiry_date"]
json.first_name user["first_name"]
json.last_name user["last_name"]
json.number_of_hold_requests user["number_of_hold_requests"]
json.number_of_loans user["number_of_loans"]
